#!/bin/bash
# Demonstration of safe push behavior

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

echo "=========================================="
echo "Safe Push Implementation - Demo Scenarios"
echo "=========================================="
echo ""

# Scenario 1: Normal Push (No Divergence)
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Scenario 1: Normal Push (No Divergence)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "$ ./pr.sh 4.1.0"
echo ""
echo -e "${GREEN}[INFO]${NC} Pushing branch to origin..."
echo -e "${GREEN}[INFO]${NC} Branch pushed successfully"
echo ""
echo "✓ Result: Push succeeds normally"
echo ""

# Scenario 2: Diverged Branch Without FORCE_PUSH
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Scenario 2: Diverged Branch (No FORCE_PUSH)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "$ ./pr.sh 4.1.0"
echo ""
echo "To https://github.com/mendersoftware/mender-server.git"
echo " ! [rejected]        release-please--branches--main -> release-please--branches--main (non-fast-forward)"
echo "error: failed to push some refs to 'https://github.com/mendersoftware/mender-server.git'"
echo ""
echo -e "${YELLOW}[WARN]${NC} Branch has diverged from remote"
echo -e "${YELLOW}[WARN]${NC} Remote branch was modified by someone else"
echo -e "${GREEN}[INFO]${NC} Remote commits that will be lost:"
echo "  a1b2c3d chore: update changelog format"
echo "  d4e5f6g fix: correct version calculation"
echo ""
echo -e "${RED}[ERROR]${NC} Push rejected. Remote branch has changes."
echo -e "${RED}[ERROR]${NC}   Set FORCE_PUSH=true to override, or pull changes first with:"
echo -e "${RED}[ERROR]${NC}     git checkout release-please--branches--main && git pull origin release-please--branches--main"
echo ""
echo "✗ Result: Push fails with clear instructions"
echo ""

# Scenario 3: Diverged Branch With FORCE_PUSH=true
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Scenario 3: Diverged Branch (FORCE_PUSH=true)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "$ FORCE_PUSH=true ./pr.sh 4.1.0"
echo ""
echo "To https://github.com/mendersoftware/mender-server.git"
echo " ! [rejected]        release-please--branches--main -> release-please--branches--main (non-fast-forward)"
echo "error: failed to push some refs to 'https://github.com/mendersoftware/mender-server.git'"
echo ""
echo -e "${YELLOW}[WARN]${NC} Branch has diverged from remote"
echo -e "${YELLOW}[WARN]${NC} Remote branch was modified by someone else"
echo -e "${GREEN}[INFO]${NC} Remote commits that will be lost:"
echo "  a1b2c3d chore: update changelog format"
echo "  d4e5f6g fix: correct version calculation"
echo ""
echo -e "${YELLOW}[WARN]${NC} FORCE_PUSH=true, forcing push..."
echo "To https://github.com/mendersoftware/mender-server.git"
echo " + a1b2c3d...x9y8z7w release-please--branches--main -> release-please--branches--main (forced update)"
echo -e "${GREEN}[INFO]${NC} Force push completed"
echo ""
echo "✓ Result: Push succeeds with warning about lost commits"
echo ""

echo "=========================================="
echo "Implementation Details"
echo "=========================================="
echo ""
echo "File: .gitlab/release/pr.sh"
echo ""
echo "Key Features:"
echo "  • Normal push attempted first"
echo "  • Detects non-fast-forward rejections"
echo "  • Shows commits that will be lost"
echo "  • Requires FORCE_PUSH=true to override"
echo "  • Provides clear error messages"
echo "  • Cleans up temporary files"
echo ""
echo "Safety Guarantees:"
echo "  ✓ No silent data loss"
echo "  ✓ Explicit confirmation required"
echo "  ✓ Clear visibility of consequences"
echo "  ✓ Helpful recovery instructions"
echo ""

echo "=========================================="
echo "Code Review Highlights"
echo "=========================================="
echo ""
echo "Before (Line 170):"
echo "  git push -f origin \"\$pr_branch\" || fatal \"Failed to push branch\""
echo ""
echo "After (Lines 180-213):"
echo "  1. Try normal push with output capture"
echo "  2. Check for divergence in output"
echo "  3. Show remote commits that will be lost"
echo "  4. Check FORCE_PUSH environment variable"
echo "  5. Either fail with helpful error or force push with warning"
echo "  6. Clean up temporary files"
echo ""
